### ISSUE TITLE
is webservice.js secure?

### ISSUE THREAD

**Issue by Marak** [Marak/webservice.js#3]
**How do you plan to make webservice.js secure? (issue sent via private message)**
## response

You'd have to specify what you mean by "secure".

Security could refer to a few things in the context of webservice.js

   Support for HTTPS
   Support for Basic Auth
   Granular Role Management (resources, users, methods, verbs, etc..)
   Validation of function arguments.

It appears you are specifically concerned with argument validation? 

First off, you shouldn't ever expose any of the native node methods. This is a BAD idea ( I think I mention this @ http://blog.nodejitsu.com/create-nodejs-web-services-in-one-line ).

Secondly, the onus of validation is currently on the developers. There is no real reason you need to validate any of the incoming arguments. The idea is that you write a custom validator inside of your method handler. 

I do however; think there is improvement in this area. It could make sense to have the ability to specify a JSON schema for function arguments and add automatic validation so the developers wouldn't have to write this code. I know there are a few JSON Schema validators in the wild, not sure which is the "best" implementation. 

The question here becomes, what is the best API for implementing this? Do you specify the Schema as part of the webservice declaration? As an export of each node.js module itself? Or do you really want to declare your Schema as part of the Models which your webservice is accessing?

It's a somewhat complex question which ties in with several other features I've been contemplating. I think the "best" choice is to implement a special exports.\* namespace in each module (perhaps exports.webservice) that will specify optional information for the web-service which should be generated. We could add optional Schemas in here, as well as custom HTTP Verbs, custom URL maps, and even down the road, roles management.

What do you think of that approach?

**Comment by akidee** [comment]
1) Validation: I want that the data that will be passed as arguments is according to constraints like data type, object property definitions etc. The way you can define that is standardized in JSON Schema.

2) The question is: Are the arguments trusted?
Instead of calling a function directly, I will delegate the call to _.validateCall(fun, context, args...), that uses the function's property SCHEMA to validate the input. You do not need to use the proxy, if the data is trusted, then you save the overhead of validating big object trees. So the SCHEMA is simply "part" of the function, and serves as documentation for the arguments format.

This is how I export my API (t is the module):

```
module.api = apize.Function.createSeveral({

    splitAndStemWords: {
        func: t.splitAndStemWords_api,
        funcContext: t,
        isAsync: true
    },

    getThesaurus: {
        func: t.getThesaurus_api,
        funcContext: t,
        isAsync: true
    },

    translate: {
        func: t.translate_api,
        funcContext: t,
        isAsync: true
    },

    findLang: {
        func: t.findLang_api,
        funcContext: t,
        isAsync: false
    }
});
```

It seems that our ideas are similar. The result is an object with Connect middleware callbacks, and that's it. Now you can add several input/output formats and authentication.

I will _not_ add schema to the api/webservice definition because I want to call the functions in any other model before rendering views.
